---
- name: "Create permanent Ansible controller"
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_inventory_sources: ["localhost"]

  roles:
    - role: controller_base


  post_tasks:
    - name: "Controller creation summary"
      ansible.builtin.debug:
        msg:
          - "Controller created successfully."
          - "Environment: {{ controller_env }}"
          - "Ansible Core version: {{ controller_ansible_core_version }}"
          - "Controller project root: {{ controller_project_root }}"
          - "Controller virtualenv: {{ controller_venv_root }}"
          - "Controller manifest: {{ controller_project_root }}/CONTROLLER.yml"
