---
- name: Ensure controller venv root exists
  file:
    path: "{{ controller_venv_root }}"
    state: directory
    mode: "0755"

- name: Ensure versioned Ansible virtualenv exists
  pip:
    virtualenv: "{{ controller_venv_root }}/{{ controller_ansible_core_version }}"
    virtualenv_command: python3 -m venv
    name:
      - "ansible-core=={{ controller_ansible_core_version }}"
